# Helmfile for StackEye deployment
# Usage:
#   helmfile -e dev apply     # Deploy to development
#   helmfile -e staging apply # Deploy to staging
#   helmfile -e prod apply    # Deploy to production

environments:
  dev:
    values:
      - namespace: stackeye-dev
      - apiHost: api.dev.stackeye.io
      - webHost: app.dev.stackeye.io
  staging:
    values:
      - namespace: stackeye-staging
      - apiHost: api.staging.stackeye.io
      - webHost: app.staging.stackeye.io
  prod:
    values:
      - namespace: stackeye
      - apiHost: api.stackeye.io
      - webHost: app.stackeye.io

---

releases:
  - name: stackeye-api
    namespace: {{ .Environment.Values.namespace }}
    chart: ./charts/stackeye-api
    values:
      - charts/stackeye-api/values.yaml
      - charts/stackeye-api/values-{{ .Environment.Name }}.yaml
    set:
      - name: ingress.hosts[0].host
        value: {{ .Environment.Values.apiHost }}
      - name: ingress.tls[0].hosts[0]
        value: {{ .Environment.Values.apiHost }}

  - name: stackeye-worker
    namespace: {{ .Environment.Values.namespace }}
    chart: ./charts/stackeye-worker
    values:
      - charts/stackeye-worker/values.yaml
      - charts/stackeye-worker/values-{{ .Environment.Name }}.yaml

  - name: stackeye-web
    namespace: {{ .Environment.Values.namespace }}
    chart: ./charts/stackeye-web
    values:
      - charts/stackeye-web/values.yaml
      - charts/stackeye-web/values-{{ .Environment.Name }}.yaml
    set:
      - name: ingress.hosts[0].host
        value: {{ .Environment.Values.webHost }}
      - name: ingress.tls[0].hosts[0]
        value: {{ .Environment.Values.webHost }}
