# Helmfile for StackEye deployment (for local development/testing only)
#
# NOTE: Production deployments use ArgoCD GitOps from stackeye-gitops repo.
# This helmfile is provided for local development and chart testing.
#
# Usage:
#   helmfile -e dev apply     # Deploy to development
#   helmfile -e staging apply # Deploy to staging
#   helmfile -e prod apply    # Deploy to production
#
# Web Frontend:
#   Web is deployed to Cloudflare Pages, not Kubernetes.
#   See: https://github.com/StackEye-IO/stackeye-web

environments:
  dev:
    values:
      - namespace: stackeye-dev
      - apiHost: api.dev.stackeye.io
  staging:
    values:
      - namespace: stackeye-staging
      - apiHost: api.staging.stackeye.io
  prod:
    values:
      - namespace: stackeye
      - apiHost: api.stackeye.io

---

releases:
  - name: stackeye-api
    namespace: {{ .Environment.Values.namespace }}
    chart: ./charts/stackeye-api
    values:
      - charts/stackeye-api/values.yaml
    set:
      - name: ingress.hosts[0].host
        value: {{ .Environment.Values.apiHost }}
      - name: ingress.tls[0].hosts[0]
        value: {{ .Environment.Values.apiHost }}

  - name: stackeye-worker
    namespace: {{ .Environment.Values.namespace }}
    chart: ./charts/stackeye-worker
    values:
      - charts/stackeye-worker/values.yaml
